name: Render Deploy

on:
  push:
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # only run if the build and tests were successful
      - uses: ttskch/render-deploy@v1.0.0
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}